/* tslint:disable */
/* eslint-disable */
/**
 * Social Media API
 * The Social Media API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ChatRoomDto
 */
export interface ChatRoomDto {

    /**
     * @type {string}
     * @memberof ChatRoomDto
     */
    id: string;

    /**
     * @type {Array<string>}
     * @memberof ChatRoomDto
     */
    members: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof ChatRoomDto
     */
    admins: Array<string>;

    /**
     * @type {string}
     * @memberof ChatRoomDto
     */
    roomType: ChatRoomDtoRoomTypeEnum;

    /**
     * @type {string}
     * @memberof ChatRoomDto
     */
    roomName?: string;

    /**
     * @type {Date}
     * @memberof ChatRoomDto
     */
    lastMessageDate: Date;

    /**
     * @type {string}
     * @memberof ChatRoomDto
     */
    roomImagePath?: string;

    /**
     * @type {Date}
     * @memberof ChatRoomDto
     */
    createdAt?: Date;

    /**
     * @type {Date}
     * @memberof ChatRoomDto
     */
    updatedAt?: Date;
}

/**
 * @export
 * @enum {string}
 */
export enum ChatRoomDtoRoomTypeEnum {
    Private = 'private',
    Group = 'group'
}

