/* tslint:disable */
/* eslint-disable */
/**
 * Social Media API
 * The Social Media API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ChatMessageDto
 */
export interface ChatMessageDto {

    /**
     * @type {string}
     * @memberof ChatMessageDto
     */
    id: string;

    /**
     * @type {string}
     * @memberof ChatMessageDto
     */
    chatRoom: string;

    /**
     * @type {string}
     * @memberof ChatMessageDto
     */
    sender: string;

    /**
     * @type {string}
     * @memberof ChatMessageDto
     */
    messageType: ChatMessageDtoMessageTypeEnum;

    /**
     * @type {string}
     * @memberof ChatMessageDto
     */
    messageStatus: ChatMessageDtoMessageStatusEnum;

    /**
     * @type {string}
     * @memberof ChatMessageDto
     */
    content?: string;

    /**
     * @type {Date}
     * @memberof ChatMessageDto
     */
    publishedAt: Date;

    /**
     * @type {Date}
     * @memberof ChatMessageDto
     */
    createdAt?: Date;

    /**
     * @type {Date}
     * @memberof ChatMessageDto
     */
    updatedAt?: Date;
}

/**
 * @export
 * @enum {string}
 */
export enum ChatMessageDtoMessageTypeEnum {
    Text = 'text',
    Image = 'image',
    Video = 'video'
}
/**
 * @export
 * @enum {string}
 */
export enum ChatMessageDtoMessageStatusEnum {
    Pending = 'pending',
    Sent = 'sent',
    Deleted = 'deleted'
}

