/* tslint:disable */
/* eslint-disable */
/**
 * Social Media API
 * The Social Media API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ChatMessageSendDto
 */
export interface ChatMessageSendDto {

    /**
     * @type {string}
     * @memberof ChatMessageSendDto
     */
    roomId: string;

    /**
     * @type {string}
     * @memberof ChatMessageSendDto
     */
    type: ChatMessageSendDtoTypeEnum;

    /**
     * @type {string}
     * @memberof ChatMessageSendDto
     */
    content?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum ChatMessageSendDtoTypeEnum {
    Text = 'text',
    Image = 'image',
    Video = 'video'
}

