/* tslint:disable */
/* eslint-disable */
/**
 * Social Media API
 * The Social Media API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CommentWriterDto } from './comment-writer-dto';
import { TranslateResultDto } from './translate-result-dto';
 /**
 * 
 *
 * @export
 * @interface CommentDataWithLikedDto
 */
export interface CommentDataWithLikedDto {

    /**
     * @type {boolean}
     * @memberof CommentDataWithLikedDto
     */
    liked: boolean;

    /**
     * @type {string}
     * @memberof CommentDataWithLikedDto
     */
    id: string;

    /**
     * @type {number}
     * @memberof CommentDataWithLikedDto
     */
    likes: number;

    /**
     * @type {CommentWriterDto}
     * @memberof CommentDataWithLikedDto
     */
    writer: CommentWriterDto;

    /**
     * @type {string}
     * @memberof CommentDataWithLikedDto
     */
    post: string;

    /**
     * @type {string}
     * @memberof CommentDataWithLikedDto
     */
    parent?: string;

    /**
     * @type {TranslateResultDto}
     * @memberof CommentDataWithLikedDto
     */
    content: TranslateResultDto;

    /**
     * @type {Date}
     * @memberof CommentDataWithLikedDto
     */
    createdAt: Date;
}
