/* tslint:disable */
/* eslint-disable */
/**
 * Social Media API
 * The Social Media API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreatePostRequestDto
 */
export interface CreatePostRequestDto {

    /**
     * @type {string}
     * @memberof CreatePostRequestDto
     */
    content: string;

    /**
     * @type {string}
     * @memberof CreatePostRequestDto
     */
    postMimeType: CreatePostRequestDtoPostMimeTypeEnum;

    /**
     * @type {number}
     * @memberof CreatePostRequestDto
     */
    size: number;
}

/**
 * @export
 * @enum {string}
 */
export enum CreatePostRequestDtoPostMimeTypeEnum {
    Videomp4 = 'video/mp4',
    Videoquicktime = 'video/quicktime',
    Imagepng = 'image/png',
    Imagejpeg = 'image/jpeg'
}

