/* tslint:disable */
/* eslint-disable */
/**
 * Social Media API
 * The Social Media API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ChatMessageDto } from './chat-message-dto';
import { PaginatedDto } from './paginated-dto';
 /**
 * 
 *
 * @export
 * @interface InlineResponse2004
 */
export interface InlineResponse2004 extends PaginatedDto {

    /**
     * @type {Array<ChatMessageDto>}
     * @memberof InlineResponse2004
     */
    data?: Array<ChatMessageDto>;

    /**
     * @type {number}
     * @memberof InlineResponse2004
     */
    page?: number;

    /**
     * @type {number}
     * @memberof InlineResponse2004
     */
    nextPage?: number;

    /**
     * @type {boolean}
     * @memberof InlineResponse2004
     */
    hasNextPage?: boolean;
}
