/* tslint:disable */
/* eslint-disable */
/**
 * Social Media API
 * The Social Media API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MiniUserProfile } from './mini-user-profile';
 /**
 * 
 *
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {

    /**
     * @type {Array<MiniUserProfile>}
     * @memberof InlineResponse200
     */
    data?: Array<MiniUserProfile>;

    /**
     * @type {number}
     * @memberof InlineResponse200
     */
    page?: number;

    /**
     * @type {number}
     * @memberof InlineResponse200
     */
    nextPage?: number;

    /**
     * @type {boolean}
     * @memberof InlineResponse200
     */
    hasNextPage?: boolean;
}
