/* tslint:disable */
/* eslint-disable */
/**
 * Social Media API
 * The Social Media API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PaginatedDto } from './paginated-dto';
import { PostDataWithWriterDto } from './post-data-with-writer-dto';
 /**
 * 
 *
 * @export
 * @interface InlineResponse2001
 */
export interface InlineResponse2001 extends PaginatedDto {

    /**
     * @type {Array<PostDataWithWriterDto>}
     * @memberof InlineResponse2001
     */
    data?: Array<PostDataWithWriterDto>;

    /**
     * @type {number}
     * @memberof InlineResponse2001
     */
    page?: number;

    /**
     * @type {number}
     * @memberof InlineResponse2001
     */
    nextPage?: number;

    /**
     * @type {boolean}
     * @memberof InlineResponse2001
     */
    hasNextPage?: boolean;
}
