/* tslint:disable */
/* eslint-disable */
/**
 * Social Media API
 * The Social Media API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface IsFollowedDTO
 */
export interface IsFollowedDTO {

    /**
     * @type {boolean}
     * @memberof IsFollowedDTO
     */
    user1FollowedUser2: boolean;

    /**
     * @type {boolean}
     * @memberof IsFollowedDTO
     */
    user2FollowedUser1: boolean;
}
