/* tslint:disable */
/* eslint-disable */
/**
 * Social Media API
 * The Social Media API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface MiniUserProfile
 */
export interface MiniUserProfile {

    /**
     * @type {string}
     * @memberof MiniUserProfile
     */
    id: string;

    /**
     * @type {string}
     * @memberof MiniUserProfile
     */
    name: string;

    /**
     * @type {string}
     * @memberof MiniUserProfile
     */
    username: string;

    /**
     * @type {string}
     * @memberof MiniUserProfile
     */
    profilePicture: string;

    /**
     * @type {boolean}
     * @memberof MiniUserProfile
     */
    following: boolean;
}
