/* tslint:disable */
/* eslint-disable */
/**
 * Social Media API
 * The Social Media API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TranslateResultDto } from './translate-result-dto';
 /**
 * 
 *
 * @export
 * @interface PostDataDto
 */
export interface PostDataDto {

    /**
     * @type {string}
     * @memberof PostDataDto
     */
    id: string;

    /**
     * @type {string}
     * @memberof PostDataDto
     */
    user: string;

    /**
     * @type {string}
     * @memberof PostDataDto
     */
    postType: PostDataDtoPostTypeEnum;

    /**
     * @type {string}
     * @memberof PostDataDto
     */
    postStatus: PostDataDtoPostStatusEnum;

    /**
     * @type {TranslateResultDto}
     * @memberof PostDataDto
     */
    content: TranslateResultDto;

    /**
     * @type {Array<string>}
     * @memberof PostDataDto
     */
    hashtags: Array<string>;

    /**
     * @type {string}
     * @memberof PostDataDto
     */
    url: string;

    /**
     * @type {Date}
     * @memberof PostDataDto
     */
    publishedAt: Date;

    /**
     * @type {number}
     * @memberof PostDataDto
     */
    likes: number;

    /**
     * @type {number}
     * @memberof PostDataDto
     */
    comments: number;

    /**
     * @type {number}
     * @memberof PostDataDto
     */
    views: number;

    /**
     * @type {boolean}
     * @memberof PostDataDto
     */
    liked: boolean;
}

/**
 * @export
 * @enum {string}
 */
export enum PostDataDtoPostTypeEnum {
    Image = 'image',
    Video = 'video'
}
/**
 * @export
 * @enum {string}
 */
export enum PostDataDtoPostStatusEnum {
    Inprogress = 'inprogress',
    Published = 'published',
    Failed = 'failed'
}

