/* tslint:disable */
/* eslint-disable */
/**
 * Social Media API
 * The Social Media API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ObjectId } from './object-id';
 /**
 * 
 *
 * @export
 * @interface Test
 */
export interface Test {

    /**
     * @type {ObjectId}
     * @memberof Test
     */
    id: ObjectId;

    /**
     * @type {number}
     * @memberof Test
     */
    v: number;

    /**
     * @type {string}
     * @memberof Test
     */
    name: string;

    /**
     * @type {number}
     * @memberof Test
     */
    age: number;
}
