/* tslint:disable */
/* eslint-disable */
/**
 * Social Media API
 * The Social Media API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateUserProfilePictureDTO
 */
export interface UpdateUserProfilePictureDTO {

    /**
     * Top offset of the image
     *
     * @type {number}
     * @memberof UpdateUserProfilePictureDTO
     * @example 0
     */
    top: number;

    /**
     * Left offset of the image
     *
     * @type {number}
     * @memberof UpdateUserProfilePictureDTO
     * @example 0
     */
    left: number;

    /**
     * Width and height of the image
     *
     * @type {number}
     * @memberof UpdateUserProfilePictureDTO
     * @example 100
     */
    size: number;

    /**
     * @type {Blob}
     * @memberof UpdateUserProfilePictureDTO
     */
    file: Blob;
}
