/* tslint:disable */
/* eslint-disable */
/**
 * Social Media API
 * The Social Media API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TranslateResultDto } from './translate-result-dto';
 /**
 * 
 *
 * @export
 * @interface User
 */
export interface User {

    /**
     * @type {string}
     * @memberof User
     */
    username: string;

    /**
     * @type {string}
     * @memberof User
     */
    name: string;

    /**
     * @type {string}
     * @memberof User
     */
    email: string;

    /**
     * @type {string}
     * @memberof User
     */
    password: string;

    /**
     * @type {string}
     * @memberof User
     */
    role: string;

    /**
     * @type {string}
     * @memberof User
     */
    profilePicture: string;

    /**
     * @type {TranslateResultDto}
     * @memberof User
     */
    about: TranslateResultDto;

    /**
     * @type {string}
     * @memberof User
     */
    language: string;

    /**
     * @type {number}
     * @memberof User
     */
    followerCount: number;

    /**
     * @type {number}
     * @memberof User
     */
    followingCount: number;

    /**
     * @type {number}
     * @memberof User
     */
    postCount: number;

    /**
     * @type {Date}
     * @memberof User
     */
    createdAt: Date;

    /**
     * @type {Date}
     * @memberof User
     */
    updatedAt: Date;
}
